using Entities;
using Microsoft.EntityFrameworkCore;
using Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestProject
{
    public class OrderRepositoryIntegrationTests : IClassFixture<DatabaseFixture>
    {
        private readonly ApiDBContext _dbContext;
        private readonly OrderRepository _orderRepository;
        public OrderRepositoryIntegrationTests(DatabaseFixture databaseFixture)
        {
            _dbContext = databaseFixture.Context;
            _orderRepository = new OrderRepository(_dbContext);
        }
        [Fact]
        public async Task GetOrderById_ReturnsOrderWithItems_WhenIdExists()
        {
            // Arrange
            _dbContext.OrderItems.RemoveRange(_dbContext.OrderItems);
            _dbContext.Orders.RemoveRange(_dbContext.Orders);
            _dbContext.Products.RemoveRange(_dbContext.Products);
            _dbContext.Users.RemoveRange(_dbContext.Users);
            await _dbContext.SaveChangesAsync();

            var user = new User { FirstName = "Test User", Email = "test@example.com", Password = "123" };
            var category = new Category { Name = "General" };
            await _dbContext.Users.AddAsync(user);
            await _dbContext.Categories.AddAsync(category);
            await _dbContext.SaveChangesAsync();

            var product = new Product { ProductName = "Test Product", CategoryId = category.Id, Price = 10.0 };
            await _dbContext.Products.AddAsync(product);
            await _dbContext.SaveChangesAsync();

            var order = new Order
            {
                UserId = user.Id,
                OrderDate = DateOnly.FromDateTime(DateTime.Now),
                OrderSum = 10.0,
                OrderItems = new List<OrderItem>
            {
                new OrderItem { ProductId = product.Id, Quantity = 1 }
            }
            };
            await _dbContext.Orders.AddAsync(order);
            await _dbContext.SaveChangesAsync();

            // Act
            var result = await _orderRepository.GetOrderById(order.Id);

            // Assert
            Assert.NotNull(result);
            Assert.Equal(order.Id, result.Id);
            Assert.Single(result.OrderItems); // Verifies .Include(o => o.OrderItems) worked
        }

        [Fact]
        public async Task GetOrderById_ReturnsNull_WhenIdDoesNotExist()
        {
            // Act
            var result = await _orderRepository.GetOrderById(9999);

            // Assert
            Assert.Null(result);
        }
        [Fact]
        public async Task AddOrder_PersistsOrderAndItemsToDatabase()
        {
            // Arrange
            _dbContext.OrderItems.RemoveRange(_dbContext.OrderItems);
            _dbContext.Orders.RemoveRange(_dbContext.Orders);
            await _dbContext.SaveChangesAsync();

            var user = new User { FirstName = "Buyer", Email = "buy@test.com", Password = "123" };
            var category = new Category { Name = "General" };
            await _dbContext.Users.AddAsync(user);
            await _dbContext.Categories.AddAsync(category);
            await _dbContext.SaveChangesAsync();

            var product = new Product { ProductName = "Gadget", CategoryId = category.Id, Price = 100.0 };
            await _dbContext.Products.AddAsync(product);
            await _dbContext.SaveChangesAsync();

            var newOrder = new Order
            {
                UserId = user.Id,
                OrderDate = DateOnly.FromDateTime(DateTime.Now),
                OrderSum = 100.0,
                OrderItems = new List<OrderItem>
            {
                new OrderItem { ProductId = product.Id, Quantity = 1 }
            }
            };

            // Act
            var result = await _orderRepository.AddOrder(newOrder);

            // Assert
            Assert.NotEqual(0, result.Id); // Verify ID was generated by SQL
            var dbOrder = await _dbContext.Orders.Include(o => o.OrderItems).FirstOrDefaultAsync(o => o.Id == result.Id);
            Assert.NotNull(dbOrder);
            Assert.Single(dbOrder.OrderItems);
        }
    }
}
